### ISSUE TITLE
Please implement a remove(T obj) capability

### ISSUE THREAD

**Issue by hellovai** [christojalh/tree-and-map#3]
https://github.com/christojalh/tree-and-map/blob/6bbdaa86402b7742e80dc5ba3744c79b01dcba63/basicmap.h#L10

I sure would think it'd be useful to remove random nodes from your graph. Lets see if you can do it!

**Comment by jleechristopher** [comment]
challenge accepted

**Comment by jleechristopher** [comment]
added remove() functionality
